- name: Deploy Flask Notes App
  hosts: web
  become: yes

  tasks:
    - name: Install system dependencies
      apt:
        name:
          - python3-pip
          - git
          - postgresql-client
        update_cache: yes

    - name: Clone the Flask Notes repo
      git:
        repo: https://github.com/archi1912/Flask_Notes_App.git
        dest: /home/{{ ansible_user }}/flask_notes_app
        version: main

    - name: Install Python dependencies
      pip:
        requirements: /home/{{ ansible_user }}/flask_notes_app/requirements.txt

    - name: Create .env file with DB variables
      template:
        src: .env.j2
        dest: /home/{{ ansible_user }}/flask_notes_app/.env

    - name: Create systemd service file
      copy:
        dest: /etc/systemd/system/flaskapp.service
        content: |
          [Unit]
          Description=Flask Notes App
          After=network.target

          [Service]
          User=ubuntu
          WorkingDirectory=/home/ubuntu/flask_notes_app
          EnvironmentFile=/home/ubuntu/flask_notes_app/.env
          ExecStart=/usr/bin/python3 app.py
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd and enable flask service
      systemd:
        name: flaskapp
        enabled: yes
        daemon_reload: yes
        state: restarted
