- name: Deploy Flask Notes App
  hosts: web
  become: yes

  tasks:
    - name: Install system dependencies
      apt:
        name:
          - python3-pip
          - git
          - postgresql-client
        update_cache: yes

    - name: Clone the Flask Notes repo
      git:
        repo: https://github.com/<your-username>/<your-repo>.git
        dest: /home/{{ ansible_user }}/flask_notes_app
        version: main

    - name: Install Python dependencies
      pip:
        requirements: /home/{{ ansible_user }}/flask_notes_app/requirements.txt

    - name: Create .env file with DB variables
      template:
        src: .env.j2
        dest: /home/{{ ansible_user }}/flask_notes_app/.env

    - name: Run the Flask app (for testing)
      shell: |
        nohup python3 /home/{{ ansible_user }}/flask_notes_app/app.py > flask.log 2>&1 &
